### ISSUE TITLE
Clicking on links on the top of the page in some cases crashes gui app

### ISSUE THREAD

**Issue by branislavvukelic** [atomia/puppetmaster-gui#136]
![image](https://user-images.githubusercontent.com/9530822/27280339-ddf65894-54e7-11e7-9d17-c9ad1edd52d8.png)

**Comment by branislavvukelic** [comment]
Jun 19 06:16:24 puppetmaster node[15991]: /opt/puppetmaster-gui/app/node_modules/mysql/lib/protocol/Parser.js:79
Jun 19 06:16:24 puppetmaster node[15991]:         throw err; // Rethrow non-MySQL errors
Jun 19 06:16:24 puppetmaster node[15991]:         ^
Jun 19 06:16:24 puppetmaster node[15991]: TypeError: Cannot read property 'json_data' of undefined
Jun 19 06:16:24 puppetmaster node[15991]:     at PlatformOption.getEnvironmentFromDatabase.error.message (/opt/puppetmaster-gui/app/puppet-config/index.js:11:46)
Jun 19 06:16:24 puppetmaster node[15991]:     at /opt/puppetmaster-gui/app/platform-options/model.js:60:5
Jun 19 06:16:24 puppetmaster node[15991]:     at Query._callback (/opt/puppetmaster-gui/app/lib/database_helper.js:16:9)
Jun 19 06:16:24 puppetmaster node[15991]:     at Query.Sequence.end (/opt/puppetmaster-gui/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
Jun 19 06:16:24 puppetmaster node[15991]:     at Query._handleFinalResultPacket (/opt/puppetmaster-gui/app/node_modules/mysql/lib/protocol/sequences/Query.js:137:8)
Jun 19 06:16:24 puppetmaster node[15991]:     at Query.EofPacket (/opt/puppetmaster-gui/app/node_modules/mysql/lib/protocol/sequences/Query.js:121:8)
Jun 19 06:16:24 puppetmaster node[15991]:     at Protocol._parsePacket (/opt/puppetmaster-gui/app/node_modules/mysql/lib/protocol/Protocol.js:280:23)
Jun 19 06:16:24 puppetmaster node[15991]:     at Parser.write (/opt/puppetmaster-gui/app/node_modules/mysql/lib/protocol/Parser.js:75:12)
Jun 19 06:16:24 puppetmaster node[15991]:     at Protocol.write (/opt/puppetmaster-gui/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
Jun 19 06:16:24 puppetmaster node[15991]:     at Socket.<anonymous> (/opt/puppetmaster-gui/app/node_modules/mysql/lib/Connection.js:103:28)
Jun 19 06:16:24 puppetmaster systemd[1]: puppetmaster-gui.service: Main process exited, code=exited, status=1/FAILURE
Jun 19 06:16:24 puppetmaster systemd[1]: puppetmaster-gui.service: Unit entered failed state.
Jun 19 06:16:24 puppetmaster systemd[1]: puppetmaster-gui.service: Failed with result 'exit-code'.

**Comment by branislavvukelic** [comment]
This bug became obsolete with refactored v1 of installer
