### ISSUE TITLE
"VIEW REQUIREMENTS LIST" button doesn't work

### ISSUE THREAD

**Issue by branislavvukelic** [atomia/puppetmaster-gui#140]
![image](https://user-images.githubusercontent.com/9530822/27287766-0dde0ab2-5505-11e7-9f8d-ec3db39600ec.png)

**Comment by branislavvukelic** [comment]
Throws: 
Jun 19 15:35:53 puppetmaster node[1670]: TypeError: Cannot read property 'length' of undefined
Jun 19 15:35:53 puppetmaster node[1670]:     at Function.PlatformOption.updateEnvironmentData (/opt/puppetmaster-gui/app/platform-options/model.js:85:43)
Jun 19 15:35:53 puppetmaster node[1670]:     at /opt/puppetmaster-gui/app/platform-options/index.js:48:20
Jun 19 15:35:53 puppetmaster node[1670]:     at Layer.handle [as handle_request] (/opt/puppetmaster-gui/app/node_modules/express/lib/router/layer.js:95:5)
Jun 19 15:35:53 puppetmaster node[1670]:     at next (/opt/puppetmaster-gui/app/node_modules/express/lib/router/route.js:137:13)
Jun 19 15:35:53 puppetmaster node[1670]:     at Route.dispatch (/opt/puppetmaster-gui/app/node_modules/express/lib/router/route.js:112:3)
Jun 19 15:35:53 puppetmaster node[1670]:     at Layer.handle [as handle_request] (/opt/puppetmaster-gui/app/node_modules/express/lib/router/layer.js:95:5)
Jun 19 15:35:53 puppetmaster node[1670]:     at /opt/puppetmaster-gui/app/node_modules/express/lib/router/index.js:281:22
Jun 19 15:35:53 puppetmaster node[1670]:     at Function.process_params (/opt/puppetmaster-gui/app/node_modules/express/lib/router/index.js:335:12)
Jun 19 15:35:53 puppetmaster node[1670]:     at next (/opt/puppetmaster-gui/app/node_modules/express/lib/router/index.js:275:10)
Jun 19 15:35:53 puppetmaster node[1670]:     at Function.handle (/opt/puppetmaster-gui/app/node_modules/express/lib/router/index.js:174:3)

**Comment by branislavvukelic** [comment]
This bug became obsolete with refactored v1 of installer
