### ISSUE TITLE
Opening Server Pre-flight check page crashes gui

### ISSUE THREAD

**Issue by branislavvukelic** [atomia/puppetmaster-gui#146]
![image](https://user-images.githubusercontent.com/9530822/27341657-2d763c30-55de-11e7-8ae4-99fcdbc0194e.png)

**Comment by branislavvukelic** [comment]
Jun 20 17:27:58 puppetmaster node[2730]: Example app listening on port 3000!
Jun 20 17:28:19 puppetmaster node[2730]: undefined:1
Jun 20 17:28:19 puppetmaster node[2730]: undefined
Jun 20 17:28:19 puppetmaster node[2730]: ^
Jun 20 17:28:19 puppetmaster node[2730]: SyntaxError: Unexpected token u in JSON at position 0
Jun 20 17:28:19 puppetmaster node[2730]:     at Object.parse (native)
Jun 20 17:28:19 puppetmaster node[2730]:     at Request._callback (/opt/puppetmaster-gui/app/pre-flight/model.js:68:26)
Jun 20 17:28:19 puppetmaster node[2730]:     at Request.self.callback (/opt/puppetmaster-gui/app/node_modules/request/request.js:188:22)
Jun 20 17:28:19 puppetmaster node[2730]:     at emitTwo (events.js:106:13)
Jun 20 17:28:19 puppetmaster node[2730]:     at Request.emit (events.js:191:7)
Jun 20 17:28:19 puppetmaster node[2730]:     at Request.<anonymous> (/opt/puppetmaster-gui/app/node_modules/request/request.js:1171:10)
Jun 20 17:28:19 puppetmaster node[2730]:     at emitOne (events.js:96:13)
Jun 20 17:28:19 puppetmaster node[2730]:     at Request.emit (events.js:188:7)
Jun 20 17:28:19 puppetmaster node[2730]:     at IncomingMessage.<anonymous> (/opt/puppetmaster-gui/app/node_modules/request/request.js:1091:12)
Jun 20 17:28:19 puppetmaster node[2730]:     at IncomingMessage.g (events.js:292:16)
Jun 20 17:28:19 puppetmaster systemd[1]: puppetmaster-gui.service: Main process exited, code=exited, status=1/FAILURE
Jun 20 17:28:19 puppetmaster systemd[1]: puppetmaster-gui.service: Unit entered failed state.
Jun 20 17:28:19 puppetmaster systemd[1]: puppetmaster-gui.service: Failed with result 'exit-code'.

**Comment by branislavvukelic** [comment]
This bug became obsolete with refactored v1 of installer
